<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>SysAdminsMedia.BlazorIconify</AssemblyName>
        <RootNamespace>SysAdminsMedia.BlazorIconify</RootNamespace>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageId>SysAdminsMedia.BlazorIconify</PackageId>
        <Authors>SysAdmins Media</Authors>
        <RepositoryUrl>https://github.com/sysadminsmedia/BlazorIconify</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <Company>SysAdmins Media</Company>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <LangVersion>latestmajor</LangVersion>
        <Version>1.1.0</Version>
        <Copyright>MIT</Copyright>
        <PackageProjectUrl>https://github.com/sysadminsmedia/BlazorIconify</PackageProjectUrl>
        <PackageLicenseUrl></PackageLicenseUrl>
        <PackageTags>blazor, icons, iconify</PackageTags>
        <Title>BlazorIconify</Title>
        <Description>The whole range of Iconify Icons in brought to Blazor</Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.1" />
        <None Include="README.md" Pack="true" PackagePath="\"/>
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.1" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.1" />
    </ItemGroup>

</Project>
